modLoader = "javafml"
loaderVersion = "[31,)"

authors = "${author}"
license = "${license}"
issueTrackerURL = "${issuesURL}"

[[mods]]
modId = "customwindowtitle"
version = "${version}"
displayName = "${name}"
description = "${description}"
displayURL = "${sourcesURL}"

[[dependencies.customwindowtitle]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.customwindowtitle]]
modId = "forge"
mandatory = true
versionRange = "[31.2.45,)"
ordering = "NONE"
side = "CLIENT"
